# Generated by Django 5.0.1 on 2024-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_remove_telegramuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
